# Generated by Django 4.0.5 on 2023-02-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('direccion', models.IntegerField()),
            ],
        ),
    ]
