# Generated by Django 4.0.5 on 2023-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0002_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsale',
            name='calle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
