# Generated by Django 4.0.5 on 2023-03-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0003_onsale_calle'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsale',
            name='foto2',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='onsale',
            name='foto3',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
