# Generated by Django 4.0.5 on 2023-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0004_onsale_foto2_onsale_foto3_alter_houses_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='baths',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='beds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
