# Generated by Django 4.0.5 on 2023-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0005_houses_baths_houses_beds_houses_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('pic', models.ImageField(null=True, upload_to='fotos')),
                ('pic2', models.ImageField(null=True, upload_to='fotos')),
                ('pic3', models.ImageField(null=True, upload_to='fotos')),
                ('areacode', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('beds', models.IntegerField(null=True)),
                ('baths', models.IntegerField(null=True)),
            ],
        ),
    ]
