# Generated by Django 4.0.5 on 2023-05-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
