# Generated by Django 4.0.5 on 2023-05-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0010_onsale_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='Agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onsale.agentes'),
        ),
    ]
