# Generated by Django 4.0.5 on 2023-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0014_agentes_facebook_agentes_linkedin_agentes_twiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentes',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentes',
            name='twiter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
