# Generated by Django 4.0.5 on 2023-05-13 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0015_alter_agentes_facebook_alter_agentes_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
