# Generated by Django 4.0.5 on 2023-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0017_alter_houses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='foto2',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
