# Generated by Django 4.0.5 on 2023-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0018_houses_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='foto3',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
