# Generated by Django 4.0.5 on 2023-05-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0019_houses_foto3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(max_length=250, null=True)),
            ],
        ),
    ]
