# Generated by Django 4.0.5 on 2023-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0022_alter_contacto_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
