# Generated by Django 4.0.5 on 2023-06-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onsale', '0023_alter_houses_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='Agente',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Onsale',
        ),
    ]
